services:
  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////app/data/exl_financial_intelligence.db
      RAW_DATA_DIR: /app/data/raw/EXL
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./tests:/app/tests
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
